[BACK] User Authentication API [SEM - 12]
Ditmar/api_sem_g2 pull request #3
Opened 2023-12-04 07:46 UTC by mayrachumacero

...

2023-12-08 04:31 UTC, Ditmar requested changes
todo el codigo esta mal hecho tienes que seguir las pautas del codigo base no puedes simplemente romperlo todo

2023-12-08 04:31 UTC, Ditmar commented on src/main.ts
> +const mongodb_1 = require("mongodb");
borra este codigo generado, no se como hiciste para aparecer este codigo, si es que usaste algun agente de IA o algo parecido pero pierde completamente el contexto, de lo que se prentede hacer

2023-12-08 04:31 UTC, Ditmar commented on src/main.ts
> +    const CreateUser = (user) => __awaiter(void 0, void 0, void 0, function* () {
lo mismo aqui

2023-12-08 04:31 UTC, Ditmar commented on src/main.ts
> +    const FindAllUsers = () => __awaiter(void 0, void 0, void 0, function* () {
lo mismo , basicamente rompiste toda la implementacion

2023-12-11 13:47 UTC, mayrachumacero commented on src/main.ts
> +const mongodb_1 = require("mongodb");
ingeniero buenos dias disculpe ya hice arreglos sera que me puede ver xfavor

2023-12-12 12:49 UTC, mayrachumacero commented
> todo el código este mal hecho tienes que seguir las pautas del código base no puedes simplemente romperlo todo

ingeniero buenos dias ya lo corregi sera que me puede revisar por favor

2023-12-12 12:50 UTC, mayrachumacero commented on src/main.ts
> +    const FindAllUsers = () => __awaiter(void 0, void 0, void 0, function* () {
igeniero ya lo corregi puede ver si esta bien o si tengo que corregir algo mas xfavor

2023-12-12 22:06 UTC, Ditmar approved these changes
NIce work!!

2023-12-12 22:07 UTC, merged